name: Publish

on: 
  workflow_dispatch

jobs:
  build-binaries:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
      - uses: docker/setup-qemu-action@v3
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        name: Set up QEMU
      - run: python -m pip install cibuildwheel
      - run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
          CIBW_ARCHS_LINUX: "auto aarch64 ppc64le"
      - uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
          if-no-files-found: error
  source:
    runs-on: ubuntu-22.04
    needs: build-binaries # dont publish source until we're sure binary builds worked
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
      - run: python -m pip install build
      - run: python -m build --sdist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
  publish-binaries:
    runs-on: ubuntu-22.04
    needs: [build-binaries, source]
    steps:
      - uses: actions/download-artifact@v3
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          packages_dir: artifact
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
