name: Publish

on: 
  workflow_dispatch:
    inputs:
      pypi_access_token:
        description: 'Temporary pypi access token'     
        required: true

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15, macos-11]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install cibuildwheel==2.1.1
      - run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "cp33 cp34 cp27-*"
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
          CIBW_ARCHS_LINUX: "auto aarch64"
      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheelhouse
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ github.event.inputs.pypi_access_token }}
          skip_existing: true
